Implement CI releases for new release/tagging policies (#41)
* Implement CI releases for new release/tagging policies

* Fixup on docker publish script

* Switch to horizenlabs/ci-base

diff --git a/.github/actions/build-docker-image/action.yml b/.github/actions/build-docker-image/action.yml
--- a/.github/actions/build-docker-image/action.yml
+++ b/.github/actions/build-docker-image/action.yml
@@ -11,10 +11,30 @@ inputs:
     description: "Docker image name"
     required: true
     type: string
+  docker_image_suffix:
+    description: "Docker image name suffix"
+    type: string
+    default: ''
   docker_hub_org:
     description: "Docker hub organization"
     type: string
     default: 'zkverify'
+  type:
+    description: "Type of docker image. If 'node' compile the node, otherwise just the given runtime [mainnet|volta]"
+    type: string
+    default: 'node'
+  profile:
+    description: "Build profile"
+    type: string
+    default: 'production'
+  features:
+    description: "Build features"
+    type: string
+    default: 'metadata-hash'
+  dry_run:
+    description: "Dry run execution"
+    type: boolean
+    default: false
 
 outputs:
   artifact_name:
@@ -34,24 +54,42 @@ runs:
       shell: bash
       run: |
         echo "Building VFlow Docker image"
-        docker build --build-arg PROFILE=production \
-          --build-arg FEATURES=metadata-hash \
-          -f "docker/dockerfiles/vflow-node.Dockerfile" \
-          -t ${{ inputs.docker_hub_org }}/${{ inputs.docker_image_name }} .
+        runtime_build_arg=""
+        if [ "${{ inputs.type }}" = "node" ]; then
+          dockerfile="vflow-node.Dockerfile"
+          runtime_build_arg=""
+        elif [ "${{ inputs.type }}" = "mainnet" ]; then
+          dockerfile="vflow-runtime.Dockerfile"
+          runtime_build_arg='--build-arg "RUNTIME_CRATE=vflow-mainnet-runtime"'
+        elif [ "${{ inputs.type }}" = "volta" ]; then
+          dockerfile="vflow-runtime.Dockerfile"
+          runtime_build_arg='--build-arg "RUNTIME_CRATE=vflow-volta-runtime"'
+        else 
+          echo "Invalid type specified: ${{ inputs.type }}. Valid values are: [node|mainnet|volta]"
+          exit 1
+        fi
+        ${{inputs.dry_run}} && echo "*********************** Dry run mode enabled, skipping Docker build [${dockerfile},'${runtime_build_arg}'] . ***********************"
+        ${{inputs.dry_run}} || docker build --build-arg "PROFILE=${{ inputs.profile }}" \
+          --build-arg "FEATURES=${{ inputs.features }}" \
+          ${runtime_build_arg} \
+          -f "docker/dockerfiles/${dockerfile}" \
+          -t ${{ inputs.docker_hub_org }}/${{ inputs.docker_image_name }}${{ inputs.docker_image_suffix }} .
 
-        echo "DOCKER_IMAGE_NAME=${{ inputs.docker_hub_org }}/${{ inputs.docker_image_name }}" >> "${GITHUB_ENV}"
+        echo "DOCKER_IMAGE_NAME=${{ inputs.docker_hub_org }}/${{ inputs.docker_image_name }}${{ inputs.docker_image_suffix }}" >> "${GITHUB_ENV}"
 
     - name: Save the Docker image as a tarball
       id: create-tar-file
       shell: bash
       run: |
-        ARTIFACT_NAME="${{ inputs.docker_image_name }}"
+        ARTIFACT_NAME="${{ inputs.docker_image_name }}${{ inputs.docker_image_suffix }}"
         TAR_FILE="${{github.workspace}}/${ARTIFACT_NAME}.tar"
 
         echo "artifact_name=$ARTIFACT_NAME" >> "${GITHUB_OUTPUT}"
         echo "TAR_FILE=$TAR_FILE" >> "${GITHUB_ENV}"
 
-        docker save "${DOCKER_IMAGE_NAME}" -o "${TAR_FILE}"
+        ${{inputs.dry_run}} && echo "*********************** Dry run mode enabled, skipping Docker build. ***********************"
+        ${{inputs.dry_run}} && echo "DRY-RUN -> ${DOCKER_IMAGE_NAME} -- ${{ inputs.type }}" > "${TAR_FILE}"
+        ${{inputs.dry_run}} || docker save "${DOCKER_IMAGE_NAME}" -o "${TAR_FILE}"
 
     - name: Upload Docker image artifact
       uses: actions/upload-artifact@v4
